name: Build LaTeX documents

on:
  push:
    paths:
      - 'cv.tex'
      - 'cv/**'
      - 'resume.tex'
      - 'resume/**'
      - 'awesome-cv.cls'
  pull_request:
    paths:
      - 'cv.tex'
      - 'cv/**'
      - 'resume.tex'
      - 'resume/**'
      - 'awesome-cv.cls'

jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            cv.tex
            resume.tex
          latexmk_use_lualatex: true

      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: pdf-files
          path: |
            cv.pdf
            resume.pdf

      - name: Commit changes
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add cv.pdf resume.pdf
          git commit -m "Update pdf files" || echo "pdf files unchanged"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
